#!/usr/bin/python

import RPi.GPIO as GPIO
from time import sleep

GPIO.setmode(GPIO.BCM)
GPIO.setup(22, GPIO.OUT)
GPIO.setup(27, GPIO.OUT)

GPIO.output(27, 1)
sleep(0.1)
GPIO.output(27, 0)

sleep(5)

GPIO.output(22, 1)
sleep(0.1)
GPIO.output(22, 0)

GPIO.cleanup()

